/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ooplTF = new javax.swing.JTextField();
        oopTF = new javax.swing.JTextField();
        dcTF = new javax.swing.JTextField();
        beTF = new javax.swing.JTextField();
        belTF = new javax.swing.JTextField();
        emTF = new javax.swing.JTextField();
        hbTF = new javax.swing.JTextField();
        oopgTF = new javax.swing.JTextField();
        ooplgTF = new javax.swing.JTextField();
        dcgTF = new javax.swing.JTextField();
        begTF = new javax.swing.JTextField();
        belgTF = new javax.swing.JTextField();
        emgTF = new javax.swing.JTextField();
        hbgTF = new javax.swing.JTextField();
        avgTF = new javax.swing.JTextField();
        gpaTF = new javax.swing.JTextField();
        cpaTF = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Grade System");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 204)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Object Oriented Programming        : ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Object Oriented Programming Lab : ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Data Communication                        : ");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Basic Electronics                                : ");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Basic Electronics Lab                         : ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Engineering Mathematics                 : ");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("History Of Bangladesh                       : ");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        ooplTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        oopTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        dcTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        beTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        belTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        emTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        hbTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        oopgTF.setEditable(false);
        oopgTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        ooplgTF.setEditable(false);
        ooplgTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        dcgTF.setEditable(false);
        dcgTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        begTF.setEditable(false);
        begTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        belgTF.setEditable(false);
        belgTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        emgTF.setEditable(false);
        emgTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        hbgTF.setEditable(false);
        hbgTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        avgTF.setEditable(false);
        avgTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        gpaTF.setEditable(false);
        gpaTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        cpaTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cpaTF.setForeground(new java.awt.Color(204, 0, 0));
        cpaTF.setText("    GPA");
        cpaTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 204), 2, true));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Average");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 204), 2, true));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Course Name");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Marks");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Grade");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 2, true));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 255));
        jButton1.setText("Calculate");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hbTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(beTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(oopTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ooplTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(belTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dcTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcgTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(belgTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(ooplgTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(oopgTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(begTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(emgTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(hbgTF)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avgTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpaTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(gpaTF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(oopTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oopgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(ooplTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ooplgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(dcTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(beTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(begTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(belTF)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(belgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cpaTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hbTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hbgTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Calculate All Grades:
        
        String oopScore,ooplScore,dcScore,beScore,belScore,emScore,hbScore;
        double average;
        double gpa =0;
        oopScore = oopTF.getText();
        ooplScore = ooplTF.getText();
        dcScore = dcTF.getText();
        beScore = beTF.getText();
        belScore = belTF.getText();
        emScore = emTF.getText();
        hbScore = hbTF.getText();
        
        double oop = Double.parseDouble(oopScore);
        double oopl = Double.parseDouble(ooplScore);
        double dc = Double.parseDouble(dcScore);
        double be = Double.parseDouble(beScore);
        double bel = Double.parseDouble(belScore);
        double em = Double.parseDouble(emScore);
        double hb = Double.parseDouble(hbScore);
        
        average = ((oop+oopl+dc+be+bel+em+hb)/7);
        average = Math.round(average*100)/100.0;
        
         // For OOP
        if (oop >= 80){
            oopgTF.setText("A+");
            gpa = gpa + 5.0;
        }
        else if (oop>=70 && oop<80){
             oopgTF.setText("A-");
             gpa = gpa + 4.0;
        }
        else if (oop>=60 && oop<70){
             oopgTF.setText("B");
             gpa = gpa + 3.0;
        }    
         else if (oop>=50 && oop<60){
             oopgTF.setText("C");
             gpa = gpa + 2.0;
         }   
         else if (oop>=40 && oop<50){
             oopgTF.setText("D");
             gpa = gpa + 1.0;
         }   
         else {
             oopgTF.setText("F");
             gpa = gpa + 0;        
        }
        
         
         // For OOPL
         if (oopl >= 80){
            ooplgTF.setText("A+");
            gpa = gpa + 5.0;
        }
        else if (oopl>=70 && oopl<80){
             ooplgTF.setText("A-");
             gpa = gpa + 4.0;
        }
        else if (oopl>=60 && oopl<70){
             ooplgTF.setText("B");
             gpa = gpa + 3.0;
        }    
         else if (oopl>=50 && oopl<60){
             ooplgTF.setText("C");
             gpa = gpa + 2.0;
         }   
         else if (oopl>=40 && oopl<50){
             ooplgTF.setText("D");
             gpa = gpa + 1.0;
         }   
         else {
             ooplgTF.setText("F");
             gpa = gpa + 0;        
        }
         
         // FOR DC
          if (dc >= 80){
            dcgTF.setText("A+");
            gpa = gpa + 5.0;
        }
        else if (dc>=70 && dc<80){
             dcgTF.setText("A-");
             gpa = gpa + 4.0;
        }
        else if (dc>=60 && dc<70){
             dcgTF.setText("B");
             gpa = gpa + 3.0;
        }    
         else if (dc>=50 && dc<60){
             dcgTF.setText("C");
             gpa = gpa + 2.0;
         }   
         else if (dc>=40 && dc<50){
             dcgTF.setText("D");
             gpa = gpa + 1.0;
         }   
 
         else {
             dcgTF.setText("F");
             gpa = gpa + 0;        
        }
          
          // FOR BE
         if (be >= 80){
            begTF.setText("A+");
            gpa = gpa + 5.0;
        }
        else if (be>=70 && be<80){
             begTF.setText("A-");
             gpa = gpa + 4.0;
        }
        else if (be>=60 && be<70){
             begTF.setText("B");
             gpa = gpa + 3.0;
        }    
         else if (be>=50 && be<60){
             begTF.setText("C");
             gpa = gpa + 2.0;
         }   
         else if (be>=40 && be<50){
             begTF.setText("D");
             gpa = gpa + 1.0;
         }   
 
         else {
             begTF.setText("F");
             gpa = gpa + 0;        
        }
         
         // FOR BEL
         
          if (bel >= 80){
            belgTF.setText("A+");
            gpa = gpa + 5.0;
        }
        else if (bel>=70 && bel<80){
             belgTF.setText("A-");
             gpa = gpa + 4.0;
        }
        else if (bel>=60 && bel<70){
             belgTF.setText("B");
             gpa = gpa + 3.0;
        }    
         else if (bel>=50 && bel<60){
             belTF.setText("C");
             gpa = gpa + 2.0;
         }   
         else if (bel>=40 && bel<50){
             belgTF.setText("D");
             gpa = gpa + 1.0;
         }   
  
         else {
             belgTF.setText("F");
             gpa = gpa + 0;        
        }
          
          // FOR EM
          
           if (em >= 80){
            emgTF.setText("A+");
            gpa = gpa + 5.0;
        }
        else if (em>=70 && em<80){
             emgTF.setText("A-");
             gpa = gpa + 4.0;
        }
        else if (em>=60 && em<70){
             emgTF.setText("B");
             gpa = gpa + 3.0;
        }    
         else if (em>=50 && em<60){
             emgTF.setText("C");
             gpa = gpa + 2.0;
         }   
         else if (em>=40 && em<50){
             emgTF.setText("D");
             gpa = gpa + 1.0;
         }   
     
         else {
             emgTF.setText("F");
             gpa = gpa + 0;        
        }
           
           // FOR HB
           
            if (hb >= 80){
            hbgTF.setText("A+");
            gpa = gpa + 5.0;
        }
        else if (hb>=70 && hb<80){
             hbgTF.setText("A-");
             gpa = gpa + 4.0;
        }
        else if (hb>=60 && hb<70){
             hbgTF.setText("B");
             gpa = gpa + 3.0;
        }    
         else if (hb>=50 && hb<60){
             hbgTF.setText("C");
             gpa = gpa + 2.0;
         }   
         else if (hb>=40 && hb<50){
             hbgTF.setText("D");
             gpa = gpa + 1.0;
         }   
   
         else {
             hbgTF.setText("F");
             gpa = gpa + 0;        
        }
            gpa = (gpa/7);
            gpa = Math.round(gpa*100)/100.0;
            gpaTF.setText(Double.toString(gpa));
            avgTF.setText(Double.toString(average));
            //gpaTF.setText(Double.toString(gpa));
            //avgTF.setText(Double.toString(average));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avgTF;
    private javax.swing.JTextField beTF;
    private javax.swing.JTextField begTF;
    private javax.swing.JTextField belTF;
    private javax.swing.JTextField belgTF;
    private javax.swing.JLabel cpaTF;
    private javax.swing.JTextField dcTF;
    private javax.swing.JTextField dcgTF;
    private javax.swing.JTextField emTF;
    private javax.swing.JTextField emgTF;
    private javax.swing.JTextField gpaTF;
    private javax.swing.JTextField hbTF;
    private javax.swing.JTextField hbgTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField oopTF;
    private javax.swing.JTextField oopgTF;
    private javax.swing.JTextField ooplTF;
    private javax.swing.JTextField ooplgTF;
    // End of variables declaration//GEN-END:variables
}
